### ISSUE TITLE
Architecture override variable proposal

### ISSUE THREAD

**Issue by stenh0use** [lotia/asdf-terragrunt#15]
### Issue
M1 Macs use arm64 architecture, but for many older plugins, arm64 is not available. 

### Proposal
M1 Macs support rosetta for running x86_64 binaries, so this issue could be overcome by providing and override environment variable.

The asdf-vm plugin for hashicorp uses the following:

> ASDF_HASHICORP_OVERWRITE_ARCH: force the plugin to use a specified processor architecture rather than the automatically detected value. Useful, for example, for allowing users on M1 Macs to install amd64 binaries when there's no arm64 binary available.

Given this, as a user, you're also using the hashicorp plugins. If you're setting the above environment variable it makes sense to re-use that variable here.

I'd like to propose a change to the install file to incorporate this.

I propose two variable options:

1. ASDF_HASHICORP_OVERWRITE_ARCH
2. ASDF_TERRAGRUNT_OVERWRITE_ARCH

Please let me know which you prefer and i'll raise a PR.

**Comment by ohmer** [comment]
Have you looked at #13 ? It fixed it for me running on a AWS Graviton instance.
Been using my own fork (https://github.com/ohmer/asdf-terragrunt/) since maintainer is unresponsive.

**Comment by lotia** [comment]
@ohmer I'm sorry for my lack of response. I didn't get any notification. I'm happy to have you take over maintenance and archive my fork. I can also make a pull request on the plugins list to point to your fork if you intend to continue maintenance. My plan was to add some more tests but if I get around to it, I'll open a PR against your fork. Let me know if that works.

**Comment by lotia** [comment]
Thanks for changing the link to your fork in the plugin index @ohmer seems entirely fair since you've significantly improved it and I apologies again for my lack of response.
